name: Deploy Three-Tier Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Docker Compose dosyasını GitHub'dan çek
            curl -o /home/ubuntu/docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/Docker-Compose-Projects/docker-compose.yml

            # Docker Compose dosyasının bulunduğu dizine gidin
            cd /home/ubuntu

            # AWS kimlik bilgilerini ortam değişkeni olarak ayarla (sudo komutunun erişebilmesi için)
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"

            # ECR'ye giriş yapın
            sudo docker login --username AWS --password-stdin $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) 889597770516.dkr.ecr.us-east-1.amazonaws.com

            # Docker imajlarını ECR'den çek
            sudo docker-compose pull

            # Eski konteynerleri durdur ve kaldır
            sudo docker-compose down

            # Yeni imajlarla servisleri başlat
            sudo docker-compose up -d
