name: Deploy Three-Tier Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ECR giriş bilgileri için Docker yapılandırmasını oluştur
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 889597770516.dkr.ecr.us-east-1.amazonaws.com

            # Docker imajlarını ECR'den çek
            docker pull 889597770516.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend:latest
            docker pull 889597770516.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:latest
            docker pull mysql:8.0

            # Eski konteynerleri durdur ve kaldır
            docker-compose down

            # Yeni imajlarla servisleri başlat
            docker-compose up -d
